{% set name = "waltlabtools" %}
{% set version = "1.0.0b27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/waltlabtools-{{ version }}.tar.gz
  sha256: 192fe2c5c13cf59a254ca6520dab57bd1fc62e0c00dd40d80b5ff759e5e79ba0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy >=1.11
    - scipy >=1.7
    - pandas >=1.3
    - matplotlib-base >=3.4
    - scikit-learn >=1.2

test:
  imports:
    - waltlabtools
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A collection of tools for biomedical research assay analysis in Python.
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tylerdougan
