{% set name = "waltlabtools" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - numpy >=1.10
    - scipy >=1.3
    - matplotlib-base >3.3
    - pandas >=0.25

about:
  home: https://github.com/tylerdougan/waltlabtools
  summary: A collection of tools for biomedical research assay analysis in Python.
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://waltlabtools.readthedocs.io

extra:
  recipe-maintainers:
    - tylerdougan
