{% set name = "waltlabtools" %}
{% set version = "0.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python {{ python }}
    - setuptools
    - numpy >=1.10
    - scipy >=1.3
  host:
    - pip
    - python {{ python }}
  run:
    - python {{ python }}
    - numpy >=1.10
    - scipy >=1.3

about:
  home: "https://github.com/tylerdougan/waltlabtools"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: LICENSE
  summary: "A collection of tools for biomedical research assay analysis in Python."
  doc_url: "https://waltlabtools.readthedocs.io"
  doc_source_url: https://github.com/tylerdougan/waltlabtools/blob/main/README.rst

extra:
  recipe-maintainers:
    - tylerdougan
