{% set name = "waltlabtools" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  noarch: python
  number: 0
  string: py{{ environ.get("PY_VER") }}_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python {{ python }}
    - matplotlib>=3.3
    - numpy>=1.16
    - pandas>=0.25
    - scipy>=1.3
    - scikit-learn>=0.21
    - jax>=0.2
    - numba>=0.48
    - setuptools
  host:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - numpy >=1.16
    - scipy >=1.3
    - matplotlib-base >3.3
    - pandas >=0.25

about:
  home: https://github.com/tylerdougan/waltlabtools
  summary: A collection of tools for biomedical research assay analysis in Python.
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://waltlabtools.readthedocs.io

extra:
  recipe-maintainers:
    - tylerdougan
